#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)
#write a Bash script that will display information about subdomains.

subdomains=( "www" "lb-01" "web-01" web-02" )
domain="$1"
sub="$2"

dig_command () {
	sub=$2
	INFORMATION="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP_ADDRESS=$(echo "$INFORMATION" | awk '{print $5}')
	ARECORD=$(echo "$INFORMATION" | awk '{print $4}')

	echo -e "The subdomain $sub is a $ARECORD record and points to $IP_ADDRESS"
}

if [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		dig_command "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	dig_command "$domain" "$sub"
fi
