#!/usr/bin/env bash
#Set up a permanent redirect

# Instal nginx
sudo apt update
sudo apt install -y nginx

# Add redirect command to nginx config on line 53
sudo sed -i "53s/.*/location \/redirect_me {\n\treturn 301 http:\/\/github.com\/\;\n}/" /etc/nginx/sites-available/default

# start nginx server
sudo service nginx restart
