#!/usr/bin/env bash
#Setting up a custom http response header

# Install Nginx web server
sudo apt update
sudo apt install -y nginx

# Setup custom http response header
sudo sed -i "s/listen \[::\]:80 default_server;/&\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-enabled/default

#Restartt nginx web server
sudo service nginx restart
