#!/usr/bin/env bash
# Setup up HAproxy load balancer

# Uninstall previous HAproxy
sudo service haproxy stop
sudo apt-get purge -y haproxy

# Install HAproxy.
sudo apt update
sudo apt install -y haproxy

# Enable HAProxy to be started by the init script.
sudo sed -i '$aENABLED=1' /etc/default/haproxy

# Setup load balancing frontend and backend options
sudo sed -i '$a\\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 37297-web-01 54.144.239.142:80 check\n\tserver 37297-web-02 100.24.205.221:80 check' /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy restart
